OUT_DIR = out
DEPS = $(OUT_DIR)/deps
TARGET = $(OUT_DIR)/thesis.pdf
LATEXMK_OPTS = -lualatex \
			   -pdf \
			   -use-make \
			   -deps \
			   -recorder \
			   -latexoption=--shell-escape \
			   -latexoption=--synctex=1 \
			   -latexoption=-halt-on-error \
			   -latexoption=-file-line-error \
			   -outdir=$(OUT_DIR) \
			   -deps-out=$(DEPS)

all: $(TARGET) $(eval -include $(DEPS)) revision.tex

$(OUT_DIR)/%.pdf: %.tex
	latexmk $(LATEXMK_OPTS) $<

$(OUT_DIR)/%.pdf: %.svg
	inkscape -D -z -f $< -A $@

revision.tex:
	echo "% Autogenerated, do not edit" > $@
	echo -ne '\\newcommand{\\revisiondate}{' >> $@
	git log -1 --format=format:"%ad" --date="format:%-d.%-m.%Y%%" >> $@
	echo '}' >> $@
	echo -ne '\\newcommand{\\revision}{' >> $@
	git log -1 --format=format:"%h" >> $@
	echo '}' >> $@

.PHONY = revision.tex
