MAKEFLAGS = -j1
OUT_DIR = out
DEPS_FILE = $(OUT_DIR)/deps

ifdef RELEASE
	TARGET = $(OUT_DIR)/thesis.pdf
else
	TARGET = $(OUT_DIR)/thesis_draft.pdf
endif

SPELLTARGET = $(TARGET:%.pdf=%.odt)

LATEXMK_OPTS = -lualatex \
			   -pdf \
			   -use-make \
			   -deps \
			   -recorder \
			   -latexoption=-shell-escape \
			   -latexoption=-synctex=1 \
			   -latexoption=-halt-on-error \
			   -latexoption=-file-line-error \
			   -outdir=$(OUT_DIR) \
			   -deps-out=$(DEPS_FILE) \

all: $(OUT_DIR)/gliederung.pdf $(TARGET)

spellcheck: $(SPELLTARGET)
	languagetool -l de-DE $<

$(SPELLTARGET): $(eval -include $(DEPS_FILE))
	htlatex thesis_draft.tex "xhtml,ooffice" "ooffice/! -cmozhtf" "-coo -cvalidate"
$(TARGET:%.pdf=%.txt): 

$(TARGET): $(eval -include $(DEPS_FILE)) revision.tex

$(OUT_DIR)/%.pdf: %.tex
	latexmk $(LATEXMK_OPTS) $<

$(OUT_DIR)/%.pdf: %.svg
	inkscape -D -z -f $< -A $@

revision.tex:
	echo "% Autogenerated, do not edit" > $@
	echo -ne '\\newcommand{\\revisiondate}{' >> $@
	git log -1 --format=format:"%ad" --date="format:%-d.%-m.%Y" >> $@
	echo '}' >> $@
	echo -ne '\\newcommand{\\revision}{' >> $@
	git log -1 --format=format:"%h" >> $@
	echo '}' >> $@

clean:
	- rm -r out/*

view: $(TARGET)
	herbstclient spawn zathura \
		--synctex-forward "$(SYNCTEX_FORWARD)" \
		-x "$(SYNCTEX_EDITOR)" \
		$(CURDIR)/$<

$(OUT_DIR)/gliederung.pdf: $(TARGET)
	./toc2pdf $(@:%.pdf=%.toc) $@

.PHONY: revision.tex all clean view spellcheck
